config/routes.rb
Monster::Application.routes.draw do
  resources :photos

  root :to => "bites#index"
  
  match "/date" => "home#date"
  match "/about", :to => "home#about"
  match "/tutorial", :to => "home#tutorial"
  match "/admin", :to => "bites#admin"
  
  match "/exhibition", :to => "exhibition#index"
  match "/exhibition/date", :to => "exhibition#date"
  match "/exhibition/top_sources", :to => "exhibition#top_sources"
  
  resources :bites do 
    collection do
      get 'upload'
    end
  end

end

app/models/photo.rb
require 'open-uri'

class Photo < ActiveRecord::Base
  has_and_belongs_to_many :bites
  
  has_attached_file :data, :styles => { :medium => "500x500>", 
                                        :thumb => "60x60#" },
                           :storage => :s3, 
                           :s3_credentials => {
                             :access_key_id => S3[:key],
                             :secret_access_key => S3[:secret] },
                           :bucket => S3[:bucket],
                           :path => "photos/:id/:style.:extension",
                           :default_url => "/images/s3/photos/default_:style.png"
  
  before_create :download_remote_image
                         
  def download_remote_image
    if self.original_url
      self.data = do_download_remote_image
    end
  end
  
  def download_remote_image!
    download_remote_image
    self.save
  end
  
  private
  
    def do_download_remote_image
      io = open(URI.parse(original_url))
      return nil unless ['image/jpeg', 'image/png', 'image/gif'].include? io.content_type
      
      def io.original_filename; base_uri.path.split('/').last; end
      io.original_filename.blank? ? nil : io
    rescue # catch url errors with validations instead of exceptions (Errno::ENOENT, OpenURI::HTTPError, etc...)
      return nil
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.xml
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.xml
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.xml
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.xml
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to(@photo, :notice => 'Photo was successfully created.') }
        format.xml  { render :xml => @photo, :status => :created, :location => @photo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.xml
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to(@photo, :notice => 'Photo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.xml
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to(photos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :original_url %><br />
    <%= f.text_field :original_url %>
  </div>
  <div class="field">
    <%= f.label :data_file_name %><br />
    <%= f.text_field :data_file_name %>
  </div>
  <div class="field">
    <%= f.label :data_file_size %><br />
    <%= f.text_field :data_file_size %>
  </div>
  <div class="field">
    <%= f.label :data_content_type %><br />
    <%= f.text_field :data_content_type %>
  </div>
  <div class="field">
    <%= f.label :data_updated_at %><br />
    <%= f.datetime_select :data_updated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Original url</th>
    <th>Data file name</th>
    <th>Data file size</th>
    <th>Data content type</th>
    <th>Data updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.original_url %></td>
    <td><%= photo.data_file_name %></td>
    <td><%= photo.data_file_size %></td>
    <td><%= photo.data_content_type %></td>
    <td><%= photo.data_updated_at %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Original url:</b>
  <%= @photo.original_url %>
</p>

<p>
  <b>Data file name:</b>
  <%= @photo.data_file_name %>
</p>

<p>
  <b>Data file size:</b>
  <%= @photo.data_file_size %>
</p>

<p>
  <b>Data content type:</b>
  <%= @photo.data_content_type %>
</p>

<p>
  <b>Data updated at:</b>
  <%= @photo.data_updated_at %>
</p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>