config/routes.rb
Monster::Application.routes.draw do
  resources :photos

  root :to => "bites#index"
  
  match "/date" => "home#date"
  match "/about", :to => "home#about"
  match "/tutorial", :to => "home#tutorial"
  match "/admin", :to => "bites#admin"
  
  match "/exhibition", :to => "exhibition#index"
  match "/exhibition/date", :to => "exhibition#date"
  match "/exhibition/top_sources", :to => "exhibition#top_sources"
  
  resources :bites do 
    collection do
      get 'upload'
    end
  end

end

app/models/bite.rb
class Bite < ActiveRecord::Base
  has_and_belongs_to_many :photos
  
  scope :accessible, :conditions => { :accessible => true }
  scope :unaccessible, :conditions => { :accessible => false }
  scope :visible, :conditions => ["hidden is NULL or hidden = ?", false ]
  
  validates :url, :presence => true
  validates :image_url, :presence => true
  
  before_create :set_accessible
  before_save   :get_domain_name
  after_create  :create_photo_by_image_url
  
  def self.admin_photos
    accessible.order('created_at DESC').limit(300)
  end
  
  def self.without_photo
    joins("LEFT OUTER JOIN bites_photos ON bites_photos.bite_id = bites.id").
    where("bites_photos.photo_id IS NULL")
  end
  
  def self.today
    date = Date.today
    return public_facing.includes(:photos).on(date).order('bites.created_at DESC')
  end
  
  def self.public_on(date)
    public_facing.on(date).order('bites.created_at DESC').includes(:photos)
  end
  
  def self.public_facing
    visible.accessible
  end
  
  def self.on(date)
    where(:created_at => (date)..(date+1.day))
  end
  
  def self.top_20_sources_in_hash
    top_sources.limit(20).map { |b| [b.domain_name, b.cnt] }
  end
  
  def self.top_sources_on(date)
    top_sources.on(date)
  end
  
  def self.top_sources
    select("count(*) as cnt, domain_name").
    public_facing.group("domain_name").
    order("cnt DESC")
  end
  
  def self.count_on(date)
    public_facing.on(date).count
  end
  
  def self.all_count
    public_facing.count
  end
  
  def get_domain_name
    begin
      uri = URI.parse(URI.encode(self.url))
      self.domain_name = uri.host
    rescue
      puts "Error when parsing ID: #{self.id} URL: #{self.url}"
    end
  end
  
  def photo
    photos.first
  end
  
  def create_photo_by_image_url
    photo = Photo.create(:original_url => self.normalized_image_url)
    if photo && photo.data.exists?
      self.photos << photo
    else
      photo.destroy
      self.accessible = false
      self.save
    end  
  end
  
  def normalized_image_url
    return '' if self.image_url.blank?
    
    if self.image_url =~ /^http/
      return self.image_url
    elsif match = self.image_url.match(/^[\/][^\/].*/)
      new_image_url = match[0]
      uri = URI(self.url)
      return "http://#{uri.host}#{new_image_url}"
    # //d6kwnbvhrfby3.cloudfront.net/img/donate/donate.png
    elsif match = self.image_url.match(/^\/\/(.*)/)
      new_image_url = match[1]
      return "http://#{new_image_url}"
    elsif match = self.image_url.match(/^[\w].*/)
      return "#{self.url}/#{match[0]}"
    else
      return self.image_url
    end
  end
  
  def self.for_exhibition(date)
    top_sources = top_sources_on(date).limit(10).map { |b| { 'domain_name' => b.domain_name, 'count' => b.cnt } }
    results = { 'top_sources' => top_sources, 'bites' => [] }
    
    bites = on(date).limit(150)
    bites.each do |bite|
      if bite.photo
        result = { 'id' => "bite-#{bite.id}", "image_html" => "<img src='#{bite.photo.data.url(:thumb)}' />" }
        results['bites'] << result
      end
    end
    return results
  end
  
  protected
  
    def set_accessible
      begin
        res = HTTParty.get(URI.escape(self.normalized_image_url))
        res.code == 200 ? self.accessible = true : self.accessible = false
      rescue
        self.accessible = false
      end
      nil
    end
end

app/controllers/bites_controller.rb
class BitesController < ApplicationController
  cache_sweeper :bite_sweeper
  
  def admin
    @bites = Bite.admin_photos

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bites }
    end
  end
  
  # GET /bites
  # GET /bites.xml
  def index
    @today_date  = Date.today
    @today_count = Bite.today.count
    @today_bites = Bite.today.limit(50)
    @top_sources = Bite.top_20_sources_in_hash
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bites }
    end
  end

  # GET /bites/1
  # GET /bites/1.xml
  def show
    @bite = Bite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bite }
    end
  end

  # GET /bites/new
  # GET /bites/new.xml
  def new
    @bite = Bite.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bite }
    end
  end

  # GET /bites/1/edit
  def edit
    @bite = Bite.find(params[:id])
  end

  # POST /bites
  # POST /bites.xml
  def create
    @bite = Bite.new(params[:bite])

    respond_to do |format|
      if @bite.save
        format.html { redirect_to(@bite, :notice => 'Bite was successfully created.') }
        format.xml  { render :xml => @bite, :status => :created, :location => @bite }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bites/1
  # PUT /bites/1.xml
  def update
    @bite = Bite.find(params[:id])

    respond_to do |format|
      if @bite.update_attributes(params[:bite])
        format.html do 
          if params[:admin] == '1'
            redirect_to admin_path
          else
            redirect_to(@bite, :notice => 'Bite was successfully updated.') 
          end
        end
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bites/1
  # DELETE /bites/1.xml
  def destroy
    @bite = Bite.find(params[:id])
    @bite.destroy

    respond_to do |format|
      format.html { redirect_to(bites_url) }
      format.xml  { head :ok }
    end
  end
  
  def upload
    @bite = BiteFactory.create(params)

    respond_to do |format|
      unless @bite.new_record?
        format.html { redirect_to(@bite, :notice => 'Bite was successfully created.') }
        format.xml  { render :xml => @bite, :status => :created, :location => @bite }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bite.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/helpers/bites_helper.rb
module BitesHelper
end

app/views/bites/_form.html.erb
<%= form_for(@bite) do |f| %>
  <% if @bite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bite.errors.count, "error") %> prohibited this bite from being saved:</h2>

      <ul>
      <% @bite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :hidden %><br />
    <%= f.check_box :hidden %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bites/admin.html.erb
<% @bites.each do |bite| %>
<span class="biteContainer">
  <div class=latest_image><%= image_tag bite.normalized_image_url %></div>
	<div class="bite_time">bite@ <%= bite.created_at.strftime("%m/%d/%y %R") %></div>
  <!-- <span>from <%= link_to bite.url, bite.url %></span> -->
  <%= form_for(bite) do |f| %>
    <%= hidden_field_tag :admin, '1' %>
    <div class="field">
      <%= f.label :hidden %><br />
      <%= f.check_box :hidden %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</span>
<% end %>

app/views/bites/edit.html.erb
<h1>Editing bite</h1>

<%= render 'form' %>

<%= link_to 'Show', @bite %> |
<%= link_to 'Back', bites_path %>

app/views/bites/index.html.erb
<center>
  <div id="main" class="clear_fix">
  	<div class="content">
		
  		<div id="latest_label">Latest 50 Bites of Today</div>
		
  		<div class="today">
  			<div class="left_col left">
  				<div class="date">
  				  <%= link_to @today_count, date_path(:date => @today_date.strftime("%Y%m%d")), :id => 'count' %>
  				</div>
  			</div>
		
  			<div class="img_container">
  			  <% unless @today_bites.empty? %>
  			  <%= link_to date_path(:date => @today_date.strftime("%Y%m%d")) do %>
    			  <% @today_bites.each do |bite| %>
    			    <span><%= image_tag bite.photo.data.url(:thumb) unless bite.photo.nil? %></span>
    			  <% end %>
  			  <% end %>
  			  <% end %>
  			</div>
			
  			<div class="clear"></div>
  		</div>
		
  		<% cache("date-archive", :expires_in => 6.hours) do %>
  		<div id="calendar">
  			<div class="month clear">
  				<div id="archive">Archive</div>
  			</div>
			
  			<% months = [] %>
  			<% @today_date.month.downto(1) { |n| months << n } %>			  
  			<% months[0..-1].each do |month| %>  			
    			<% down_from_this_date = (months.index(month) == 0 ? (@today_date - 1.day) : Date.civil(2012, month, -1)) %>
    			<div class="month clear_fix">
    				<div class="title left"><%= Date::ABBR_MONTHNAMES[month] %> 2012</div>
    				<div class="dates_container left <%= @today_date.month == month ? '' : 'hidden' %>">
    				  <div class="dates clear_fix">
        				<% down_from_this_date.downto(Date.civil(2012, month, 1)) do |date| %>
        				<div class="date">
        					<%= link_to Bite.count_on(date), date_path(:date => date.strftime("%Y%m%d")), :class => 'count' %>
        					<div class="time"><%= date.day.ordinalize %></div>
        				</div>
        				<% end %>
        			</div>
      			</div>
    			</div>
  			<% end %>			
  		</div>
      <% end %>
  	</div>
	
  	<div class="ip_list">		
  	  <div class="section">
    		<div class="title">Top 20 Sites</div>
    		<%= render :partial => 'shared/top_sources', :locals => { :top_sources => @top_sources } %>
    	</div>
  	
    	<div class="section">
  		  <div class="title">Total Bites</div>
  		  <%= Bite.all_count %>
  		</div>
  	</div>

  </div>	
</center>

<div id="menu">
	<span id="monster_wall"><a href="/" class="selected">Monster Wall</a></span> /
	<span id="monster_about"><a href="/about">About</a></span>
</div>

app/views/bites/new.html.erb
<h1>New bite</h1>

<%= render 'form' %>

<%= link_to 'Back', bites_path %>

app/views/bites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @bite.url %>
</p>

<p>
  <b>Image url:</b>
  <%= @bite.image_url %>
</p>


<%= link_to 'Edit', edit_bite_path(@bite) %> |
<%= link_to 'Back', bites_path %>